---
apiVersion: v1
kind: Service
metadata:
  name: pki-auth-gateway
  namespace: pki-system
  labels:
    app: pki-auth-gateway
spec:
  selector:
    app: pki-auth-gateway
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer

