---
apiVersion: v1
kind: Service
metadata:
  name: pki-postgres
  namespace: pki-system
  labels:
    app: pki-postgres
spec:
  selector:
    app: pki-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP

